# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c43ba2e240f190613beb28a2b43d8e165b9b2bf50b7653847c40ce3a0c8201edeca89282e52e4290e787bbf2e429e1a60f177b2a9b05a078dd741a813de3c2cf

test:
  secret_key_base: e14e78f8e74dbad4b0de5b2a668a37c0463c2f3f722089d7ff5499264a90a3b3647cd34810ecfcd7a96fa0fa2c94f05610336e84a7150765ec1aeed4d542db99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
